sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t ljinan/frontend -f Dockerfile.dev .

script:
  #- docker run -e CT=true ljinan/frontend npm run test
  - docker run ljinan/frontend npm run test -- --coverage
