sudo: required
services:
  - docker

before_install:
  - cd frontend
  #- docker build -t ljinan/frontend -f Dockerfile.dev .
  - docker build -t ljinan/frontend -f Dockerfile .

script:
  - docker run -e CT=true ljinan/frontend npm run test -- --watchAll=false
  #- docker run ljinan/frontend npm run test -- --coverage

Deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "Frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-273354642381"
  bucket_path: "Frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"